<a href="https://colab.research.google.com/github/Shashank-ravi46/Shashank-R/blob/main/IBM_%20Palantir%20Financial_Statement_Modeling_and_Valuation_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# CELL 1
# This installs the Python tools we need.
# You only need to run this once when you open the notebook.

!pip -q install edgartools plotly pandas numpy requests

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 35.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 60.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 12.2 MB/s eta 0:00:00

In [3]:
# CELL 2
# This brings the tools into your notebook so Python can use them.

import pandas as pd
import numpy as np
import requests
import plotly.express as px

print("Good job — your libraries loaded correctly.")

Good job — your libraries loaded correctly.

In [4]:
# CELL 3
# This is just a tiny test to prove Colab is working.

company_name = "IBM"
number = 5

print("Hello Shashank")
print("We are building a model for", company_name)
print("2 + 3 =", 2 + 3)
print("number times 10 =", number * 10)

Hello Shashank
We are building a model for IBM
2 + 3 = 5
number times 10 = 50

In [5]:
# CELL 4
# This cell tries to find IBM in EdgarTools.

from edgar import Company

ibm = Company("IBM")

print("Success — we found the company.")
print(ibm)

Success — we found the company.
Company(CIK=51143)

In [10]:
# FIX CELL
# EdgarTools often needs your identity before it can pull SEC data.

from edgar import set_identity, Company

set_identity("Shashank Ravi rshashank46@gmail.com")

ibm = Company("IBM")

print("Identity set successfully.")
print("IBM object rebuilt successfully.")
print(ibm)

Identity set successfully.
IBM object rebuilt successfully.
Company(CIK=51143)

In [11]:
# CELL 5 — SAFER VERSION

financials = ibm.get_financials()

print("We asked IBM for financials.")

print("\nType of financials object:")
print(type(financials))

print("\nTrying to access statements...")

income_statement = financials.income_statement()
balance_sheet = financials.balance_sheet()
cash_flow = financials.cashflow_statement()

print("\nSUCCESS — statements loaded.")
print("\nINCOME STATEMENT:")
print(income_statement)

print("\nBALANCE SHEET:")
print(balance_sheet)

print("\nCASH FLOW:")
print(cash_flow)

We asked IBM for financials.

Type of financials object:
<class 'edgar.financials.Financials'>

Trying to access statements...

SUCCESS — statements loaded.

INCOME STATEMENT:

                               INTERNATIONAL BUSINESS MACHINES CORPORATION   IBM 96
                               CONSOLIDATED STATEMENT OF INCOME
                               Dec 31, 2023 to Dec 31, 2025

                                                                     Dec 31, 2025   Dec 31, 2024   Dec 31, 2023
   ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
            Revenue:                                                      $67,535        $62,753        $61,860
            Services                                                      $30,714        $29,813        $30,378
            Sales                                                         $36,085        $32,231        $30,745
            Financing                                                        $737           $709           $737
            Cost:                                                         $28,239        $27,201        $27,560
            Services                                                      $20,975        $20,529        $21,051
            Sales                                                          $6,861         $6,303         $6,127
            Financing                                                        $403           $369           $382
          Gross profit                                                    $39,297        $35,551        $34,300
        Expense and other (income)
            Selling, general and administrative:                          $20,123        $19,688        $19,003
            Research and development                                       $8,316         $7,479         $6,775
            Intellectual property and custom development income            $(964)         $(996)         $(860)
            Other (income) and expense:                                    $(442)         $1,871         $(914)
            Interest expense:                                              $1,935         $1,712         $1,607
              Total expense and other (income):                           $28,968        $29,754        $25,610
            Income from continuing operations before income taxes:         10,328          5,797          8,690
            Provision for/(benefit from) income taxes                      $(242)         $(218)         $1,176
          Income from continuing operations                                10,571          6,015          7,514
          Income/(loss) from discontinued operations, net of tax               22              8           (12)
          Net income:                                                     $10,593         $6,023         $7,502
        Earnings/(loss) per share of common stock
          Assuming dilution
                Continuing operations (in dollars per share)                11.14           6.42           8.15
                Discontinued operations (in dollars per share)               0.02           0.01          -0.01
              Total (in dollars per share)                                  11.17           6.43           8.14
          Basic
                Continuing operations (in dollars per share)                11.34           6.53           8.25
                Discontinued operations (in dollars per share)               0.02           0.01          -0.01
              Total (in dollars per share)                                  11.36           6.53           8.23
        Weighted-average number of common shares outstanding
            Assuming dilution (in shares)                             948,675,228    937,161,224    922,073,828
            Basic (in shares)                                         932,293,927    921,767,834    911,210,319

   Source: SEC XBRL  •  (In millions, except shares in actual amounts and per share data)


BALANCE SHEET:

                                        INTERNATIONAL BUSINESS MACHINES CORPORATION   IBM 96
                                        CONSOLIDATED BALANCE SHEETS
                                        Dec 31, 2024 to Dec 31, 2025

                                                                                                      Dec 31, 2025   Dec 31, 2024
   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    Assets
      Current assets
            Cash and cash equivalents                                                                      $13,587        $13,947
            Restricted cash                                                                                    $54           $214
            Marketable securities:                                                                            $830           $644
            Notes and accounts receivable—trade (net of allowances of $99 in 2025 and $114 in 2024)         $8,112         $6,804
        Short-term financing receivables
            Held for investment (net of allowances of $106 in 2025 and $109 in 2024)                        $7,344         $6,259
            Held for sale                                                                                   $1,131           $900
            Other accounts receivable (net of allowances of $37 in 2025 and $31 in 2024)                    $1,052           $947
            Inventory                                                                                       $1,220         $1,289
            Deferred costs                                                                                  $1,084           $959
            Prepaid expenses and other current assets                                                       $2,530         $2,520
          Total current assets                                                                             $36,944        $34,482
          Property, plant and equipment:                                                                   $17,874        $17,691
          Land and land improvements                                                                          $182           $179
          Buildings and building and leasehold improvements                                                 $4,807         $4,825
          Information technology equipment                                                                  $8,885         $8,895
          Production, engineering, office and other equipment                                               $4,000         $3,792
          Less: Accumulated depreciation                                                                   $11,975        $11,959
          Property, plant and equipment—net                                                                 $5,899         $5,731
          Operating right-of-use assets—net:                                                                $3,129         $3,197
          Long-term financing receivables (net of allowances of $34 in 2025 and $19 in 2024)                $7,708         $5,353
          Prepaid pension assets:                                                                           $7,544         $7,492
          Deferred costs                                                                                      $825           $788
          Deferred taxes                                                                                    $8,610         $6,978
          Goodwill:                                                                                        $67,717        $60,706
          Intangible assets—net:                                                                           $11,391        $10,660
          Investments and sundry assets                                                                     $2,112         $1,787
        Total assets                                                                                      $151,880       $137,175
    Liabilities and equity
      Current liabilities
            Taxes                                                                                           $2,347         $2,033
            Short-term debt                                                                                 $6,424         $5,089
            Accounts payable                                                                                $4,756         $4,032
            Compensation and benefits                                                                       $4,114         $3,605
            Deferred income                                                                                $16,101        $13,907
            Operating lease liabilities                                                                       $800           $768
            Other accrued expenses and liabilities                                                          $4,116         $3,709
          Total current liabilities                                                                        $38,658        $33,142
          Long-term debt                                                                                   $54,836        $49,884
          Retirement and nonpension postretirement benefit obligations:                                     $9,018         $9,432
          Deferred income                                                                                   $4,271         $3,622
          Operating lease liabilities                                                                       $2,547         $2,655
          Other liabilities                                                                                 $9,810        $11,048
          Total liabilities                                                                               $119,139       $109,783
        Commitments and Contingencies
      Equity
        IBM stockholders' equity
              Common stock and additional paid-in capital                                                  $63,318        $61,380
              Retained earnings                                                                           $155,648       $151,163
              Treasury stock, at cost (shares: 2025—1,353,666,394; 2024—1,352,874,243)                  $(170,605)     $(169,968)
              Accumulated other comprehensive income/(loss)                                              $(15,713)      $(15,269)
              Total IBM stockholders' equity                                                               $32,648        $27,307
          Noncontrolling interests                                                                             $93            $86
          Total equity:                                                                                    $32,740        $27,393
        Total liabilities and equity                                                                      $151,880       $137,175

   Source: SEC XBRL  •  (In millions, except shares and per share data)


CASH FLOW:

                                        INTERNATIONAL BUSINESS MACHINES CORPORATION   IBM 96
                                        CONSOLIDATED STATEMENT OF CASH FLOWS
                                        Dec 31, 2023 to Dec 31, 2025

                                                                                        Dec 31, 2025   Dec 31, 2024   Dec 31, 2023
   ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    Cash flows from operating activities
          Net income:                                                                        $10,593         $6,023         $7,502
      Adjustments to reconcile net income to cash provided by operating activities
          Pension settlement charges:                                                                        $3,113
          Depreciation                                                                        $2,284         $2,168         $2,109
          Amortization of capitalized software and acquired intangible assets                 $2,737         $2,499         $2,287
          Stock-based compensation                                                            $1,715         $1,311         $1,133
          Deferred taxes                                                                      $(957)       $(2,330)       $(1,114)
          Net (gain)/loss on divestitures, asset sales and other                               $(39)         $(652)         $(170)
      Change in operating assets and liabilities, net of acquisitions/divestitures
          Receivables (including financing receivables)                                     $(4,278)         $(374)           $725
          Retirement related                                                                   $(50)           $265         $(462)
          Inventory                                                                              $70         $(166)           $390
          Other assets/other liabilities                                                        $495         $1,601         $1,466
          Accounts payable                                                                      $624          $(13)            $65
        Net cash provided by operating activities                                            $13,193        $13,445        $13,931
    Cash flows from investing activities
          Payments for property, plant and equipment                                        $(1,091)       $(1,048)       $(1,245)
          Proceeds from disposition of property, plant and equipment/other:                     $121           $557           $321
          Investment in software                                                              $(647)         $(637)         $(565)
          Purchases of marketable securities and other investments                         $(10,095)       $(7,762)      $(11,143)
          Proceeds from disposition of marketable securities and other investments            $9,704         $6,544        $10,647
          Acquisition of businesses, net of cash acquired                                   $(8,294)       $(3,289)       $(5,082)
          Divestiture of businesses, net of cash transferred                                    $(1)           $698           $(4)
        Net cash provided by/(used in) investing activities                                $(10,302)       $(4,937)       $(7,070)
    Cash flows from financing activities
          Proceeds from new debt                                                              $8,391         $5,705         $9,586
          Payments to settle debt                                                           $(5,489)       $(6,615)       $(5,082)
          Short-term borrowings/(repayments) less than 90 days—net                             $(29)            $30           $(7)
          Common stock repurchases for tax withholdings                                     $(1,018)         $(651)         $(402)
          Proceeds from issuance of shares                                                      $710           $745           $414
          Financing—other                                                                     $(139)         $(145)         $(239)
          Cash dividends paid                                                               $(6,255)       $(6,147)       $(6,040)
        Net cash provided by/(used in) financing activities                                 $(3,829)       $(7,079)       $(1,769)
        Effect of exchange rate changes on cash, cash equivalents and restricted cash           $418         $(359)             $9
      Net change in cash, cash equivalents and restricted cash                                $(520)         $1,071         $5,101
      Cash, cash equivalents and restricted cash at January 1                                $14,160        $13,089         $7,988
      Cash, cash equivalents and restricted cash at December 31                              $13,640        $14,160        $13,089
    Supplemental data
        Income taxes paid—net of refunds received                                             $1,948         $1,723         $1,564
        Interest paid on debt                                                                 $2,042         $1,978         $1,668

   Source: SEC XBRL  •  (In millions, except shares and per share data)

In [12]:
# CELL 6
# Turn IBM statements into tables (DataFrames)

income_df = income_statement.to_dataframe()
balance_df = balance_sheet.to_dataframe()
cashflow_df = cash_flow.to_dataframe()

print("Success — we turned the statements into tables.")

print("\nINCOME DF SHAPE:")
print(income_df.shape)

print("\nBALANCE DF SHAPE:")
print(balance_df.shape)

print("\nCASH FLOW DF SHAPE:")
print(cashflow_df.shape)

Success — we turned the statements into tables.

INCOME DF SHAPE:
(85, 19)

BALANCE DF SHAPE:
(108, 18)

CASH FLOW DF SHAPE:
(46, 19)

In [13]:
# CELL 7
# Show the first few rows so we can actually see the table

print("INCOME STATEMENT TABLE:")
display(income_df.head())

print("\nBALANCE SHEET TABLE:")
display(balance_df.head())

print("\nCASH FLOW TABLE:")
display(cashflow_df.head())

INCOME STATEMENT TABLE:

,concept,label,standard_concept,2025-12-31 (FY),2024-12-31 (FY),2023-12-31 (FY),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_Revenues,Revenue,Revenue,6.753500e+10,6.275300e+10,6.186000e+10,4,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
1,us-gaap_Revenues,Services,None,3.071400e+10,2.981300e+10,3.037800e+10,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_TechnologyServiceMember,Services,srt:ProductOrServiceAxis: Services,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
2,us-gaap_Revenues,Sales,None,3.608500e+10,3.223100e+10,3.074500e+10,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_ProductMember,Sales,srt:ProductOrServiceAxis: Sales,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
3,us-gaap_Revenues,Financing,None,7.370000e+08,7.090000e+08,7.370000e+08,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_FinancialServiceMember,Financing,srt:ProductOrServiceAxis: Financing,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
4,us-gaap_Revenues,Americas,None,3.334200e+10,3.126600e+10,3.166600e+10,4,False,True,True,srt:StatementGeographicalAxis,srt_AmericasMember,Americas,srt:StatementGeographicalAxis: Americas,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems

BALANCE SHEET TABLE:

,concept,label,standard_concept,2025-12-31,2024-12-31,level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_AssetsAbstract,Assets,None,NaN,NaN,1,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_StatementOfFinancialPositionAbstract
1,us-gaap_AssetsCurrentAbstract,Current assets,None,NaN,NaN,2,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_AssetsAbstract
2,us-gaap_CashAndCashEquivalentsAtCarryingValue,Cash and cash equivalents,CashAndMarketableSecurities,1.358700e+10,1.394700e+10,4,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract
3,us-gaap_RestrictedCash,Restricted cash,RestrictedCashCurrent,5.400000e+07,2.140000e+08,4,False,False,False,None,None,None,None,None,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract
4,us-gaap_DebtSecuritiesAvailableForSaleExcludin...,Marketable securities,CashAndMarketableSecurities,8.300000e+08,6.440000e+08,4,False,False,False,None,None,None,None,None,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract

CASH FLOW TABLE:

,concept,label,standard_concept,2025-12-31 (FY),2024-12-31 (FY),2023-12-31 (FY),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,Cash flows from operating activities,None,NaN,NaN,NaN,1,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_StatementOfCashFlowsAbstract
1,us-gaap_NetIncomeLoss,Net income,NetIncome,1.059300e+10,6.023000e+09,7.502000e+09,3,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_NetCashProvidedByUsedInOperatingActivi...
2,us-gaap_NetIncomeLoss,Total IBM Stockholders’ Equity,None,1.059300e+10,6.023000e+09,7.502000e+09,3,False,True,True,us-gaap:StatementEquityComponentsAxis,us-gaap_ParentMember,Total IBM Stockholders’ Equity,us-gaap:StatementEquityComponentsAxis: Total I...,credit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_NetCashProvidedByUsedInOperatingActivi...
3,us-gaap_NetIncomeLoss,Retained Earnings,None,1.059300e+10,6.023000e+09,7.502000e+09,4,False,True,True,us-gaap:StatementEquityComponentsAxis,us-gaap_RetainedEarningsMember,Retained Earnings,us-gaap:StatementEquityComponentsAxis: Retaine...,credit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_NetCashProvidedByUsedInOperatingActivi...
4,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...,Adjustments to reconcile net income to cash pr...,None,NaN,NaN,NaN,2,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_NetCashProvidedByUsedInOperatingActivi...

In [14]:
# CELL 8
# Ask for a cleaner version of the statements

financials = ibm.get_financials()

income_statement_clean = financials.income_statement(view="summary")
balance_sheet_clean = financials.balance_sheet(view="summary")
cash_flow_clean = financials.cashflow_statement(view="summary")

print("Clean summary statements loaded.")
print("\nINCOME STATEMENT:")
print(income_statement_clean)

print("\nBALANCE SHEET:")
print(balance_sheet_clean)

print("\nCASH FLOW:")
print(cash_flow_clean)

Clean summary statements loaded.

INCOME STATEMENT:

                               INTERNATIONAL BUSINESS MACHINES CORPORATION   IBM 96
                               CONSOLIDATED STATEMENT OF INCOME
                               Dec 31, 2023 to Dec 31, 2025

                                                                     Dec 31, 2025   Dec 31, 2024   Dec 31, 2023
   ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
            Revenue:                                                      $67,535        $62,753        $61,860
            Cost:                                                         $28,239        $27,201        $27,560
          Gross profit                                                    $39,297        $35,551        $34,300
        Expense and other (income)
            Selling, general and administrative:                          $20,123        $19,688        $19,003
            Research and development                                       $8,316         $7,479         $6,775
            Intellectual property and custom development income            $(964)         $(996)         $(860)
            Other (income) and expense:                                    $(442)         $1,871         $(914)
            Interest expense:                                              $1,935         $1,712         $1,607
              Total expense and other (income):                           $28,968        $29,754        $25,610
            Income from continuing operations before income taxes:         10,328          5,797          8,690
            Provision for/(benefit from) income taxes                      $(242)         $(218)         $1,176
          Income from continuing operations                                10,571          6,015          7,514
          Income/(loss) from discontinued operations, net of tax               22              8           (12)
          Net income:                                                     $10,593         $6,023         $7,502
        Earnings/(loss) per share of common stock
          Assuming dilution
                Continuing operations (in dollars per share)                11.14           6.42           8.15
                Discontinued operations (in dollars per share)               0.02           0.01          -0.01
              Total (in dollars per share)                                  11.17           6.43           8.14
          Basic
                Continuing operations (in dollars per share)                11.34           6.53           8.25
                Discontinued operations (in dollars per share)               0.02           0.01          -0.01
              Total (in dollars per share)                                  11.36           6.53           8.23
        Weighted-average number of common shares outstanding
            Assuming dilution (in shares)                             948,675,228    937,161,224    922,073,828
            Basic (in shares)                                         932,293,927    921,767,834    911,210,319

   Source: SEC XBRL  •  (In millions, except shares in actual amounts and per share data)


BALANCE SHEET:

                                        INTERNATIONAL BUSINESS MACHINES CORPORATION   IBM 96
                                        CONSOLIDATED BALANCE SHEETS
                                        Dec 31, 2024 to Dec 31, 2025

                                                                                                      Dec 31, 2025   Dec 31, 2024
   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    Assets
      Current assets
            Cash and cash equivalents                                                                      $13,587        $13,947
            Restricted cash                                                                                    $54           $214
            Marketable securities:                                                                            $830           $644
            Notes and accounts receivable—trade (net of allowances of $99 in 2025 and $114 in 2024)         $8,112         $6,804
        Short-term financing receivables
            Held for investment (net of allowances of $106 in 2025 and $109 in 2024)                        $7,344         $6,259
            Held for sale                                                                                   $1,131           $900
            Other accounts receivable (net of allowances of $37 in 2025 and $31 in 2024)                    $1,052           $947
            Inventory                                                                                       $1,220         $1,289
            Deferred costs                                                                                  $1,084           $959
            Prepaid expenses and other current assets                                                       $2,530         $2,520
          Total current assets                                                                             $36,944        $34,482
          Property, plant and equipment:                                                                   $17,874        $17,691
          Less: Accumulated depreciation                                                                   $11,975        $11,959
          Property, plant and equipment—net                                                                 $5,899         $5,731
          Operating right-of-use assets—net:                                                                $3,129         $3,197
          Long-term financing receivables (net of allowances of $34 in 2025 and $19 in 2024)                $7,708         $5,353
          Prepaid pension assets:                                                                           $7,544         $7,492
          Deferred costs                                                                                      $825           $788
          Deferred taxes                                                                                    $8,610         $6,978
          Goodwill:                                                                                        $67,717        $60,706
          Intangible assets—net:                                                                           $11,391        $10,660
          Investments and sundry assets                                                                     $2,112         $1,787
        Total assets                                                                                      $151,880       $137,175
    Liabilities and equity
      Current liabilities
            Taxes                                                                                           $2,347         $2,033
            Short-term debt                                                                                 $6,424         $5,089
            Accounts payable                                                                                $4,756         $4,032
            Compensation and benefits                                                                       $4,114         $3,605
            Deferred income                                                                                $16,101        $13,907
            Operating lease liabilities                                                                       $800           $768
            Other accrued expenses and liabilities                                                          $4,116         $3,709
          Total current liabilities                                                                        $38,658        $33,142
          Long-term debt                                                                                   $54,836        $49,884
          Retirement and nonpension postretirement benefit obligations:                                     $9,018         $9,432
          Deferred income                                                                                   $4,271         $3,622
          Operating lease liabilities                                                                       $2,547         $2,655
          Other liabilities                                                                                 $9,810        $11,048
          Total liabilities                                                                               $119,139       $109,783
        Commitments and Contingencies
      Equity
        IBM stockholders' equity
              Common stock and additional paid-in capital                                                  $63,318        $61,380
              Retained earnings                                                                           $155,648       $151,163
              Treasury stock, at cost (shares: 2025—1,353,666,394; 2024—1,352,874,243)                  $(170,605)     $(169,968)
              Accumulated other comprehensive income/(loss)                                              $(15,713)      $(15,269)
              Total IBM stockholders' equity                                                               $32,648        $27,307
          Noncontrolling interests                                                                             $93            $86
          Total equity:                                                                                    $32,740        $27,393
        Total liabilities and equity                                                                      $151,880       $137,175

   Source: SEC XBRL  •  (In millions, except shares and per share data)


CASH FLOW:

                                        INTERNATIONAL BUSINESS MACHINES CORPORATION   IBM 96
                                        CONSOLIDATED STATEMENT OF CASH FLOWS
                                        Dec 31, 2023 to Dec 31, 2025

                                                                                        Dec 31, 2025   Dec 31, 2024   Dec 31, 2023
   ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    Cash flows from operating activities
          Net income:                                                                        $10,593         $6,023         $7,502
      Adjustments to reconcile net income to cash provided by operating activities
          Pension settlement charges:                                                                        $3,113
          Depreciation                                                                        $2,284         $2,168         $2,109
          Amortization of capitalized software and acquired intangible assets                 $2,737         $2,499         $2,287
          Stock-based compensation                                                            $1,715         $1,311         $1,133
          Deferred taxes                                                                      $(957)       $(2,330)       $(1,114)
          Net (gain)/loss on divestitures, asset sales and other                               $(39)         $(652)         $(170)
      Change in operating assets and liabilities, net of acquisitions/divestitures
          Receivables (including financing receivables)                                     $(4,278)         $(374)           $725
          Retirement related                                                                   $(50)           $265         $(462)
          Inventory                                                                              $70         $(166)           $390
          Other assets/other liabilities                                                        $495         $1,601         $1,466
          Accounts payable                                                                      $624          $(13)            $65
        Net cash provided by operating activities                                            $13,193        $13,445        $13,931
    Cash flows from investing activities
          Payments for property, plant and equipment                                        $(1,091)       $(1,048)       $(1,245)
          Proceeds from disposition of property, plant and equipment/other:                     $121           $557           $321
          Investment in software                                                              $(647)         $(637)         $(565)
          Purchases of marketable securities and other investments                         $(10,095)       $(7,762)      $(11,143)
          Proceeds from disposition of marketable securities and other investments            $9,704         $6,544        $10,647
          Acquisition of businesses, net of cash acquired                                   $(8,294)       $(3,289)       $(5,082)
          Divestiture of businesses, net of cash transferred                                    $(1)           $698           $(4)
        Net cash provided by/(used in) investing activities                                $(10,302)       $(4,937)       $(7,070)
    Cash flows from financing activities
          Proceeds from new debt                                                              $8,391         $5,705         $9,586
          Payments to settle debt                                                           $(5,489)       $(6,615)       $(5,082)
          Short-term borrowings/(repayments) less than 90 days—net                             $(29)            $30           $(7)
          Common stock repurchases for tax withholdings                                     $(1,018)         $(651)         $(402)
          Proceeds from issuance of shares                                                      $710           $745           $414
          Financing—other                                                                     $(139)         $(145)         $(239)
          Cash dividends paid                                                               $(6,255)       $(6,147)       $(6,040)
        Net cash provided by/(used in) financing activities                                 $(3,829)       $(7,079)       $(1,769)
        Effect of exchange rate changes on cash, cash equivalents and restricted cash           $418         $(359)             $9
      Net change in cash, cash equivalents and restricted cash                                $(520)         $1,071         $5,101
      Cash, cash equivalents and restricted cash at January 1                                $14,160        $13,089         $7,988
      Cash, cash equivalents and restricted cash at December 31                              $13,640        $14,160        $13,089
    Supplemental data
        Income taxes paid—net of refunds received                                             $1,948         $1,723         $1,564
        Interest paid on debt                                                                 $2,042         $1,978         $1,668

   Source: SEC XBRL  •  (In millions, except shares and per share data)

In [15]:
# CELL 9
# Turn the cleaner statements into DataFrames

income_clean_df = income_statement_clean.to_dataframe()
balance_clean_df = balance_sheet_clean.to_dataframe()
cashflow_clean_df = cash_flow_clean.to_dataframe()

print("Clean DataFrames created.")

print("\nIncome clean shape:", income_clean_df.shape)
print("Balance clean shape:", balance_clean_df.shape)
print("Cash flow clean shape:", cashflow_clean_df.shape)

Clean DataFrames created.

Income clean shape: (27, 19)
Balance clean shape: (53, 18)
Cash flow clean shape: (41, 19)

In [16]:
# CELL 10
# Show the first few rows of the cleaner tables

print("INCOME CLEAN TABLE:")
display(income_clean_df.head(10))

print("\nBALANCE CLEAN TABLE:")
display(balance_clean_df.head(10))

print("\nCASH FLOW CLEAN TABLE:")
display(cashflow_clean_df.head(10))

INCOME CLEAN TABLE:

,concept,label,standard_concept,2025-12-31 (FY),2024-12-31 (FY),2023-12-31 (FY),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_Revenues,Revenue,Revenue,6.753500e+10,6.275300e+10,6.186000e+10,4,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
1,us-gaap_CostOfRevenue,Cost,CostOfGoodsAndServicesSold,2.823900e+10,2.720100e+10,2.756000e+10,4,False,False,False,None,None,None,None,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
2,us-gaap_GrossProfit,Gross profit,GrossProfit,3.929700e+10,3.555100e+10,3.430000e+10,3,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
3,ibm_ExpenseAndOtherIncomeAbstract,Expense and other (income),None,NaN,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_StatementLineItems
4,us-gaap_SellingGeneralAndAdministrativeExpense,"Selling, general and administrative",SellingGeneralAndAdminExpenses,2.012300e+10,1.968800e+10,1.900300e+10,4,False,False,False,None,None,None,None,debit,1.0,1.0,ibm_ExpenseAndIncomeOther,ibm_ExpenseAndOtherIncomeAbstract
5,us-gaap_ResearchAndDevelopmentExpense,Research and development,ResearchAndDevelopmentExpenses,8.316000e+09,7.479000e+09,6.775000e+09,4,False,False,False,None,None,None,None,debit,1.0,1.0,ibm_ExpenseAndIncomeOther,ibm_ExpenseAndOtherIncomeAbstract
6,ibm_IntellectualPropertyAndCustomDevelopmentIn...,Intellectual property and custom development i...,None,-9.640000e+08,-9.960000e+08,-8.600000e+08,4,False,False,False,None,None,None,None,credit,-1.0,-1.0,ibm_ExpenseAndIncomeOther,ibm_ExpenseAndOtherIncomeAbstract
7,ibm_OtherExpenseAndIncome,Other (income) and expense,None,-4.420000e+08,1.871000e+09,-9.140000e+08,4,False,False,False,None,None,None,None,debit,1.0,1.0,ibm_ExpenseAndIncomeOther,ibm_ExpenseAndOtherIncomeAbstract
8,us-gaap_InterestExpense,Interest expense,InterestExpense,1.935000e+09,1.712000e+09,1.607000e+09,4,False,False,False,None,None,None,None,debit,1.0,1.0,ibm_ExpenseAndIncomeOther,ibm_ExpenseAndOtherIncomeAbstract
9,ibm_ExpenseAndIncomeOther,Total expense and other (income),None,2.896800e+10,2.975400e+10,2.561000e+10,5,False,False,False,None,None,None,None,debit,-1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,ibm_ExpenseAndOtherIncomeAbstract

BALANCE CLEAN TABLE:

,concept,label,standard_concept,2025-12-31,2024-12-31,level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_AssetsAbstract,Assets,None,NaN,NaN,1,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_StatementOfFinancialPositionAbstract
1,us-gaap_AssetsCurrentAbstract,Current assets,None,NaN,NaN,2,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_AssetsAbstract
2,us-gaap_CashAndCashEquivalentsAtCarryingValue,Cash and cash equivalents,CashAndMarketableSecurities,1.358700e+10,1.394700e+10,4,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract
3,us-gaap_RestrictedCash,Restricted cash,RestrictedCashCurrent,5.400000e+07,2.140000e+08,4,False,False,False,None,None,None,None,None,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract
4,us-gaap_DebtSecuritiesAvailableForSaleExcludin...,Marketable securities,CashAndMarketableSecurities,8.300000e+08,6.440000e+08,4,False,False,False,None,None,None,None,None,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract
5,us-gaap_AccountsReceivableNetCurrent,Notes and accounts receivable—trade (net of al...,TradeReceivables,8.112000e+09,6.804000e+09,4,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract
6,us-gaap_AccountsNotesAndLoansReceivableNetCurr...,Short-term financing receivables,None,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_AssetsCurrentAbstract
7,ibm_NotesAndLoansReceivableAndNetInvestmentInL...,Held for investment (net of allowances of $106...,None,7.344000e+09,6.259000e+09,4,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AccountsNotesAndLoansReceivableNetCurr...
8,us-gaap_TradeAndLoansReceivablesHeldForSaleNet...,Held for sale,OtherNonOperatingCurrentAssets,1.131000e+09,9.000000e+08,4,False,False,False,None,None,None,None,None,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AccountsNotesAndLoansReceivableNetCurr...
9,us-gaap_OtherReceivablesNetCurrent,Other accounts receivable (net of allowances o...,OtherNonOperatingCurrentAssets,1.052000e+09,9.470000e+08,4,False,False,False,None,None,None,None,None,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract

CASH FLOW CLEAN TABLE:

,concept,label,standard_concept,2025-12-31 (FY),2024-12-31 (FY),2023-12-31 (FY),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,Cash flows from operating activities,None,NaN,NaN,NaN,1,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_StatementOfCashFlowsAbstract
1,us-gaap_NetIncomeLoss,Net income,NetIncome,1.059300e+10,6.023000e+09,7.502000e+09,3,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_NetCashProvidedByUsedInOperatingActivi...
2,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...,Adjustments to reconcile net income to cash pr...,None,NaN,NaN,NaN,2,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_NetCashProvidedByUsedInOperatingActivi...
3,ibm_PensionSettlementCharge,Pension settlement charges,None,0.000000e+00,3.113000e+09,0.000000e+00,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
4,us-gaap_Depreciation,Depreciation,DepreciationExpense,2.284000e+09,2.168000e+09,2.109000e+09,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
5,us-gaap_AmortizationOfIntangibleAssets,Amortization of capitalized software and acqui...,AmortizationOfIntangibles,2.737000e+09,2.499000e+09,2.287000e+09,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
6,us-gaap_ShareBasedCompensation,Stock-based compensation,StockBasedCompensationExpense,1.715000e+09,1.311000e+09,1.133000e+09,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
7,us-gaap_DeferredIncomeTaxExpenseBenefit,Deferred taxes,IncomeTaxes,-9.570000e+08,-2.330000e+09,-1.114000e+09,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
8,ibm_NetGainLossOnDivestituresAssetSalesAndOther,"Net (gain)/loss on divestitures, asset sales a...",None,-3.900000e+07,-6.520000e+08,-1.700000e+08,3,False,False,False,None,None,None,None,credit,-1.0,-1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
9,us-gaap_IncreaseDecreaseInOperatingCapitalAbst...,"Change in operating assets and liabilities, ne...",None,NaN,NaN,NaN,2,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_NetCashProvidedByUsedInOperatingActivi...

In [17]:
# CELL 11
# Pull the most important line items into a small analysis table

def safe_extract_row(df, keywords):
    """
    Find the first row whose index contains any of the keywords.
    """
    if df.empty:
        return None

    idx = df.index.astype(str).str.lower()
    for keyword in keywords:
        matches = idx.str.contains(keyword, na=False)
        if matches.any():
            return df.loc[matches].iloc[0]
    return None


revenue_row = safe_extract_row(income_clean_df, ["revenue", "sales"])
net_income_row = safe_extract_row(income_clean_df, ["net income", "profit"])
gross_profit_row = safe_extract_row(income_clean_df, ["gross profit"])

summary_rows = []

if revenue_row is not None:
    summary_rows.append(("Revenue", revenue_row))
if gross_profit_row is not None:
    summary_rows.append(("Gross Profit", gross_profit_row))
if net_income_row is not None:
    summary_rows.append(("Net Income", net_income_row))

summary_table = pd.DataFrame({name: row for name, row in summary_rows}).T

print("Summary table created.")
display(summary_table)

Summary table created.

Empty DataFrame
Columns: []
Index: []

In [18]:
# CELL 12
# Create a simple chart of the key metrics

if not summary_table.empty:
    chart_df = summary_table.T
    chart_df.columns = chart_df.index.astype(str)
    chart_df = chart_df.reset_index(drop=True)

    fig = px.line(
        chart_df.T,
        title="IBM Key Financial Metrics",
        markers=True
    )
    fig.update_layout(
        template="plotly_white",
        xaxis_title="Period",
        yaxis_title="Value",
        legend_title="Metric"
    )
    fig.show()
else:
    print("Summary table is empty, so there is nothing to chart yet.")

Summary table is empty, so there is nothing to chart yet.

In [20]:
import os

# Define a directory for saving tables
TABLE_DIR = "./tables"
if not os.path.exists(TABLE_DIR):
    os.makedirs(TABLE_DIR)

# CELL 13
# Save the cleaned tables to files

income_clean_df.to_csv(os.path.join(TABLE_DIR, "ibm_income_clean.csv"))
balance_clean_df.to_csv(os.path.join(TABLE_DIR, "ibm_balance_clean.csv"))
cashflow_clean_df.to_csv(os.path.join(TABLE_DIR, "ibm_cashflow_clean.csv"))
summary_table.to_csv(os.path.join(TABLE_DIR, "ibm_summary_table.csv"))

print("Saved all IBM cleaned files.")

Saved all IBM cleaned files.

In [21]:
# CELL 14
# Pull key rows from the income statement

def find_row_by_keywords(df, keywords):
    """
    Find the first row whose index contains any keyword.
    """
    if df.empty:
        return None

    idx = df.index.astype(str).str.lower()
    for keyword in keywords:
        matches = idx.str.contains(keyword, na=False)
        if matches.any():
            return df.loc[matches].iloc[0]
    return None


revenue = find_row_by_keywords(income_clean_df, ["revenue", "sales"])
gross_profit = find_row_by_keywords(income_clean_df, ["gross profit"])
operating_income = find_row_by_keywords(income_clean_df, ["operating income", "income from operations"])
net_income = find_row_by_keywords(income_clean_df, ["net income", "profit"])

print("Revenue row found:", revenue is not None)
print("Gross profit row found:", gross_profit is not None)
print("Operating income row found:", operating_income is not None)
print("Net income row found:", net_income is not None)

Revenue row found: False
Gross profit row found: False
Operating income row found: False
Net income row found: False

In [22]:
# CELL 15
# Build a mini analysis table

analysis_table = pd.DataFrame()

if revenue is not None:
    analysis_table.loc["Revenue"] = revenue
if gross_profit is not None:
    analysis_table.loc["Gross Profit"] = gross_profit
if operating_income is not None:
    analysis_table.loc["Operating Income"] = operating_income
if net_income is not None:
    analysis_table.loc["Net Income"] = net_income

display(analysis_table)

Empty DataFrame
Columns: []
Index: []

In [23]:
# CELL 16
# Calculate simple margins

margins = pd.DataFrame()

if revenue is not None and gross_profit is not None:
    margins.loc["Gross Margin"] = gross_profit / revenue

if revenue is not None and operating_income is not None:
    margins.loc["Operating Margin"] = operating_income / revenue

if revenue is not None and net_income is not None:
    margins.loc["Net Margin"] = net_income / revenue

display(margins)

Empty DataFrame
Columns: []
Index: []

In [24]:
# CELL 17
# Plot the margins

if not margins.empty:
    fig = px.bar(
        margins.T,
        title="IBM Margin Snapshot",
        labels={"value": "Margin", "index": "Period"}
    )
    fig.update_layout(template="plotly_white")
    fig.show()
else:
    print("No margins available to plot.")

No margins available to plot.

In [25]:
# CELL 18
# Save analysis files

analysis_table.to_csv(os.path.join(TABLE_DIR, "ibm_analysis_table.csv"))
margins.to_csv(os.path.join(TABLE_DIR, "ibm_margins.csv"))

print("Analysis files saved.")

Analysis files saved.

In [26]:
# CELL 19
# Create simple IBM forecast assumptions

forecast_years = 5

revenue_growth_rates = [0.04, 0.035, 0.03, 0.03, 0.025]
operating_margin_assumptions = [0.17, 0.175, 0.18, 0.182, 0.185]
net_margin_assumptions = [0.12, 0.123, 0.125, 0.127, 0.13]
fcf_margin_assumptions = [0.13, 0.135, 0.14, 0.142, 0.145]

wacc = 0.09
terminal_growth = 0.025

print("Forecast assumptions created.")

Forecast assumptions created.

In [28]:
# CELL 20
# Build a simple 5-year forecast table

# Get the latest historical revenue
# To fix the AttributeError: 'NoneType' object has no attribute 'iloc'
# This error occurs because the `revenue` variable from the previous cell (CELL 14) is `None`.
# This happened because the `find_row_by_keywords` function in CELL 14 searched the DataFrame's *index* for keywords,
# but the `income_clean_df` (from which `revenue` was supposed to be extracted) has its line item names
# (e.g., 'us-gaap_Revenues') in a 'concept' column, not its numerical index.

# We need to re-extract the latest historical revenue correctly from `income_clean_df` within this cell.

latest_revenue = 0.0 # Default value in case extraction fails

if not income_clean_df.empty and 'concept' in income_clean_df.columns:
    concept_col_lower = income_clean_df['concept'].astype(str).str.lower()

    # Find the row where the 'concept' column contains "revenues"
    revenue_row_matches = concept_col_lower.str.contains("revenues", na=False)

    if revenue_row_matches.any():
        revenue_row_series = income_clean_df.loc[revenue_row_matches].iloc[0]

        # Identify columns that are not 'concept' and likely contain financial data
        financial_data_columns = [col for col in income_clean_df.columns if col != 'concept']

        # Iterate through financial columns to find the latest revenue value.
        # Assuming the latest year is in the first column of financial data displayed.
        for col in financial_data_columns:
            if col in revenue_row_series.index: # Check if column exists in the Series
                value_str = str(revenue_row_series[col]).replace('$', '').replace(',', '')
                try:
                    current_parsed_value = float(value_str)
                    # Found the latest revenue value, break the loop
                    latest_revenue = current_parsed_value
                    break
                except ValueError:
                    # Not a valid float, continue to the next column
                    continue

    if latest_revenue == 0.0:
        print("Warning: Could not extract latest numerical revenue from `income_clean_df` using 'revenues' keyword. Using 0.0 for forecast.")
else:
    print("Warning: `income_clean_df` is empty or missing 'concept' column. Using 0.0 for forecast.")

# Ensure latest_revenue is float for calculations
latest_revenue = float(latest_revenue)

forecast_data = []
current_revenue = latest_revenue

for i in range(forecast_years):
    year_label = f"Year {i+1}"

    growth = revenue_growth_rates[i]
    op_margin = operating_margin_assumptions[i]
    net_margin = net_margin_assumptions[i]
    fcf_margin = fcf_margin_assumptions[i]

    current_revenue = current_revenue * (1 + growth)
    operating_income_forecast = current_revenue * op_margin
    net_income_forecast = current_revenue * net_margin
    free_cash_flow_forecast = current_revenue * fcf_margin

    forecast_data.append({
        "Year": year_label,
        "Revenue": current_revenue,
        "Revenue Growth": growth,
        "Operating Margin": op_margin,
        "Operating Income": operating_income_forecast,
        "Net Margin": net_margin,
        "Net Income": net_income_forecast,
        "FCF Margin": fcf_margin,
        "Free Cash Flow": free_cash_flow_forecast
    })

forecast_df = pd.DataFrame(forecast_data)
display(forecast_df)

,Year,Revenue,Revenue Growth,Operating Margin,Operating Income,Net Margin,Net Income,FCF Margin,Free Cash Flow
0,Year 1,7.023640e+10,0.040,0.170,1.194019e+10,0.120,8.428368e+09,0.130,9.130732e+09
1,Year 2,7.269467e+10,0.035,0.175,1.272157e+10,0.123,8.941445e+09,0.135,9.813781e+09
2,Year 3,7.487551e+10,0.030,0.180,1.347759e+10,0.125,9.359439e+09,0.140,1.048257e+10
3,Year 4,7.712178e+10,0.030,0.182,1.403616e+10,0.127,9.794466e+09,0.142,1.095129e+10
4,Year 5,7.904982e+10,0.025,0.185,1.462422e+10,0.130,1.027648e+10,0.145,1.146222e+10

In [30]:
# CELL 21
# Calculate discounted cash flow valuation

fcf_values = forecast_df["Free Cash Flow"].values

discounted_fcfs = []
for t, fcf in enumerate(fcf_values, start=1):
    pv = fcf / ((1 + wacc) ** t)
    discounted_fcfs.append(pv)

forecast_df["Discounted FCF"] = discounted_fcfs

terminal_fcf = fcf_values[-1] * (1 + terminal_growth)
terminal_value = terminal_fcf / (wacc - terminal_growth)
discounted_terminal_value = terminal_value / ((1 + wacc) ** forecast_years)

enterprise_value = forecast_df["Discounted FCF"].sum() + discounted_terminal_value

print("Discounted forecast table:")
display(forecast_df)

print("\nTerminal Value:", terminal_value)
print("Discounted Terminal Value:", discounted_terminal_value)
print("Enterprise Value:", enterprise_value)

Discounted forecast table:

,Year,Revenue,Revenue Growth,Operating Margin,Operating Income,Net Margin,Net Income,FCF Margin,Free Cash Flow,Discounted FCF
0,Year 1,7.023640e+10,0.040,0.170,1.194019e+10,0.120,8.428368e+09,0.130,9.130732e+09,8.376818e+09
1,Year 2,7.269467e+10,0.035,0.175,1.272157e+10,0.123,8.941445e+09,0.135,9.813781e+09,8.260063e+09
2,Year 3,7.487551e+10,0.030,0.180,1.347759e+10,0.125,9.359439e+09,0.140,1.048257e+10,8.094469e+09
3,Year 4,7.712178e+10,0.030,0.182,1.403616e+10,0.127,9.794466e+09,0.142,1.095129e+10,7.758172e+09
4,Year 5,7.904982e+10,0.025,0.185,1.462422e+10,0.130,1.027648e+10,0.145,1.146222e+10,7.449659e+09

Terminal Value: 180750463268.85107
Discounted Terminal Value: 117475399166.39252
Enterprise Value: 157414580861.16687

In [32]:
# CELL 22
# Historical vs forecast revenue chart

# Re-extract historical revenue from income_clean_df to fix AttributeError
historical_revenue_data = {}
if not income_clean_df.empty and 'concept' in income_clean_df.columns:
    # Find the row corresponding to 'Revenues'
    revenue_row_df = income_clean_df[income_clean_df['concept'].str.contains('revenues', case=False, na=False)]

    if not revenue_row_df.empty:
        # Get columns that represent financial years (e.g., '2023-12-31 (FY)')
        financial_year_columns = [col for col in revenue_row_df.columns if 'FY' in col and '-' in col]

        # Sort columns to ensure they are in chronological order for plotting
        financial_year_columns_sorted = sorted(financial_year_columns, key=lambda x: int(x.split('-')[0]))

        # Extract values and use just the year for the period label
        for col in financial_year_columns_sorted:
            year_label = col.split('-')[0] # e.g., '2023' from '2023-12-31 (FY)'
            value_str = str(revenue_row_df[col].iloc[0]).replace('$', '').replace(',', '')
            try:
                historical_revenue_data[year_label] = float(value_str)
            except ValueError:
                # Skip if value cannot be converted to float
                continue

# Create a Series for historical revenue
historical_revenue_series = pd.Series(historical_revenue_data)

# Prepare historical_chart_df
historical_chart_df = pd.DataFrame({
    "Period": historical_revenue_series.index.astype(str), # Ensure periods are strings
    "Revenue": historical_revenue_series.values,
    "Type": "Historical"
})

# Prepare forecast_chart_df
forecast_revenue = forecast_df[["Year", "Revenue"]].copy()
forecast_revenue.columns = ["Period", "Revenue"]

forecast_chart_df = pd.DataFrame({
    "Period": forecast_revenue["Period"],
    "Revenue": forecast_revenue["Revenue"],
    "Type": "Forecast"
})

# Combine and plot
combined_chart_df = pd.concat([historical_chart_df, forecast_chart_df], ignore_index=True)

fig = px.line(
    combined_chart_df,
    x="Period",
    y="Revenue",
    color="Type",
    markers=True,
    title="IBM Historical and Forecast Revenue"
)

fig.update_layout(template="plotly_white")
fig.show()

In [33]:
# CELL 23
# Save forecast outputs

forecast_df.to_csv(os.path.join(TABLE_DIR, "ibm_forecast.csv"), index=False)

dcf_summary = pd.DataFrame([{
    "Terminal Value": terminal_value,
    "Discounted Terminal Value": discounted_terminal_value,
    "Enterprise Value": enterprise_value
}])

dcf_summary.to_csv(os.path.join(TABLE_DIR, "ibm_dcf_summary.csv"), index=False)

print("IBM forecast and DCF files saved.")

IBM forecast and DCF files saved.

In [34]:
# CELL 24
# Reusable company loader

def load_company_financials(ticker):
    company = Company(ticker)
    financials = company.get_financials()

    income_stmt = financials.income_statement(view="summary")
    balance_stmt = financials.balance_sheet(view="summary")
    cashflow_stmt = financials.cashflow_statement(view="summary")

    income_df = income_stmt.to_dataframe()
    balance_df = balance_stmt.to_dataframe()
    cashflow_df = cashflow_stmt.to_dataframe()

    return {
        "ticker": ticker,
        "company": company,
        "financials": financials,
        "income_stmt": income_stmt,
        "balance_stmt": balance_stmt,
        "cashflow_stmt": cashflow_stmt,
        "income_df": income_df,
        "balance_df": balance_df,
        "cashflow_df": cashflow_df
    }

print("Reusable loader created.")

Reusable loader created.

In [35]:
# CELL 25
# Load Palantir financials

pltr_data = load_company_financials("PLTR")

print("Loaded:", pltr_data["ticker"])
print("Income shape:", pltr_data["income_df"].shape)
print("Balance shape:", pltr_data["balance_df"].shape)
print("Cash flow shape:", pltr_data["cashflow_df"].shape)

Loaded: PLTR
Income shape: (20, 19)
Balance shape: (34, 18)
Cash flow shape: (35, 19)

In [36]:
# CELL 26
# Preview Palantir statements

print("PLTR INCOME:")
display(pltr_data["income_df"].head(10))

print("\nPLTR BALANCE SHEET:")
display(pltr_data["balance_df"].head(10))

print("\nPLTR CASH FLOW:")
display(pltr_data["cashflow_df"].head(10))

PLTR INCOME:

,concept,label,standard_concept,2025-12-31 (FY),2024-12-31 (FY),2023-12-31 (FY),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_RevenueFromContractWithCustomerExcludi...,Revenue,Revenue,4.475446e+09,2.865507e+09,2.225012e+09,2,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_IncomeStatementAbstract
1,us-gaap_CostOfRevenue,Cost of revenue,CostOfGoodsAndServicesSold,7.891770e+08,5.659900e+08,4.311050e+08,2,False,False,False,None,None,None,None,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_IncomeStatementAbstract
2,us-gaap_GrossProfit,Gross profit,GrossProfit,3.686269e+09,2.299517e+09,1.793907e+09,1,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_OperatingIncomeLoss,us-gaap_IncomeStatementAbstract
3,us-gaap_OperatingExpensesAbstract,Operating expenses:,None,NaN,NaN,NaN,1,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_IncomeStatementAbstract
4,us-gaap_SellingAndMarketingExpense,Sales and marketing,SellingGeneralAndAdminExpenses,1.056859e+09,8.877550e+08,7.449920e+08,2,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
5,us-gaap_ResearchAndDevelopmentExpense,Research and development,ResearchAndDevelopmentExpenses,5.576770e+08,5.078780e+08,4.046240e+08,2,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
6,us-gaap_GeneralAndAdministrativeExpense,General and administrative,SellingGeneralAndAdminExpenses,6.577180e+08,5.934810e+08,5.243250e+08,2,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
7,us-gaap_OperatingExpenses,Total operating expenses,TotalOperatingExpenses,2.272254e+09,1.989114e+09,1.673941e+09,3,False,False,False,None,None,None,None,None,-1.0,1.0,us-gaap_OperatingIncomeLoss,us-gaap_OperatingExpensesAbstract
8,us-gaap_OperatingIncomeLoss,Income from operations,OperatingIncomeLoss,1.414015e+09,3.104030e+08,1.199660e+08,2,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_IncomeStatementAbstract
9,us-gaap_InvestmentIncomeInterest,Interest income,InterestAndDividendIncome,-2.291810e+08,-1.967920e+08,-1.325720e+08,2,False,False,False,None,None,None,None,credit,1.0,-1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_IncomeStatementAbstract

PLTR BALANCE SHEET:

,concept,label,standard_concept,2025-12-31,2024-12-31,level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_AssetsAbstract,Assets,None,NaN,NaN,1,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_StatementOfFinancialPositionAbstract
1,us-gaap_AssetsCurrentAbstract,Current assets:,None,NaN,NaN,2,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_AssetsAbstract
2,us-gaap_CashAndCashEquivalentsAtCarryingValue,Cash and cash equivalents,CashAndMarketableSecurities,1.423796e+09,2.098524e+09,4,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract
3,us-gaap_MarketableSecuritiesCurrent,Marketable securities,ShortTermInvestments,5.753247e+09,3.131463e+09,4,False,False,False,None,None,None,None,None,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract
4,us-gaap_AccountsReceivableNetCurrent,"Accounts receivable, net",TradeReceivables,1.042065e+09,5.750480e+08,4,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract
5,us-gaap_PrepaidExpenseAndOtherAssetsCurrent,Prepaid expenses and other current assets,OtherNonOperatingCurrentAssets,1.390660e+08,1.292540e+08,4,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_AssetsCurrentAbstract
6,us-gaap_AssetsCurrent,Total current assets,CurrentAssetsTotal,8.358174e+09,5.934289e+09,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_Assets,us-gaap_AssetsCurrentAbstract
7,us-gaap_PropertyPlantAndEquipmentNet,"Property and equipment, net",PlantPropertyEquipmentNet,5.196000e+07,3.963800e+07,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_Assets,us-gaap_AssetsAbstract
8,us-gaap_OperatingLeaseRightOfUseAsset,Operating lease right-of-use assets,OperatingLeaseRightOfUseAsset,2.001050e+08,2.007400e+08,3,False,False,False,None,None,None,None,None,1.0,1.0,us-gaap_Assets,us-gaap_AssetsAbstract
9,us-gaap_OtherAssetsNoncurrent,Other assets,OtherNonOperatingNonCurrentAssets,2.901530e+08,1.662170e+08,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_Assets,us-gaap_AssetsAbstract

PLTR CASH FLOW:

,concept,label,standard_concept,2025-12-31 (FY),2024-12-31 (FY),2023-12-31 (FY),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,Operating activities,None,NaN,NaN,NaN,1,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_StatementOfCashFlowsAbstract
1,us-gaap_ProfitLoss,Net income,ProfitLoss,1.634644e+09,467918000.0,217375000.0,3,False,False,False,None,None,None,None,None,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_NetCashProvidedByUsedInOperatingActivi...
2,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...,Adjustments to reconcile net income to net cas...,None,NaN,NaN,NaN,2,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_NetCashProvidedByUsedInOperatingActivi...
3,us-gaap_DepreciationDepletionAndAmortization,Depreciation and amortization,DepreciationExpense,2.614500e+07,31587000.0,33354000.0,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
4,us-gaap_ShareBasedCompensation,Stock-based compensation,StockBasedCompensationExpense,6.840330e+08,691638000.0,475903000.0,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
5,us-gaap_DebtAndEquitySecuritiesUnrealizedGainLoss,Unrealized and realized (gain) loss from marke...,NonoperatingIncomeExpense,2.122800e+07,19306000.0,13160000.0,3,False,False,False,None,None,None,None,None,-1.0,-1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
6,pltr_NoncashConsideration,Noncash consideration,None,-3.724400e+07,-52521000.0,-46609000.0,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
7,us-gaap_OtherOperatingActivitiesCashFlowStatement,Other operating activities,NetCashFromOperatingActivities,1.563000e+07,66034000.0,12764000.0,3,False,False,False,None,None,None,None,None,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
8,us-gaap_IncreaseDecreaseInOperatingCapitalAbst...,Changes in operating assets and liabilities:,None,NaN,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,None,us-gaap_AdjustmentsToReconcileNetIncomeLossToC...
9,us-gaap_IncreaseDecreaseInAccountsReceivable,"Accounts receivable, net",None,-4.504290e+08,-211157000.0,-106159000.0,4,False,False,False,None,None,None,None,None,-1.0,-1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_IncreaseDecreaseInOperatingCapitalAbst...

In [37]:
# CELL 27
# Extract Palantir key rows

pltr_revenue = find_row_by_keywords(pltr_data["income_df"], ["revenue", "sales"])
pltr_gross_profit = find_row_by_keywords(pltr_data["income_df"], ["gross profit"])
pltr_operating_income = find_row_by_keywords(pltr_data["income_df"], ["operating income", "income from operations"])
pltr_net_income = find_row_by_keywords(pltr_data["income_df"], ["net income", "profit"])

print("Revenue row found:", pltr_revenue is not None)
print("Gross profit row found:", pltr_gross_profit is not None)
print("Operating income row found:", pltr_operating_income is not None)
print("Net income row found:", pltr_net_income is not None)

Revenue row found: False
Gross profit row found: False
Operating income row found: False
Net income row found: False

In [38]:
# CELL 28
# Build Palantir analysis table

pltr_analysis_table = pd.DataFrame()

if pltr_revenue is not None:
    pltr_analysis_table.loc["Revenue"] = pltr_revenue
if pltr_gross_profit is not None:
    pltr_analysis_table.loc["Gross Profit"] = pltr_gross_profit
if pltr_operating_income is not None:
    pltr_analysis_table.loc["Operating Income"] = pltr_operating_income
if pltr_net_income is not None:
    pltr_analysis_table.loc["Net Income"] = pltr_net_income

display(pltr_analysis_table)

Empty DataFrame
Columns: []
Index: []

In [39]:
# CELL 29
# Calculate Palantir margins

pltr_margins = pd.DataFrame()

if pltr_revenue is not None and pltr_gross_profit is not None:
    pltr_margins.loc["Gross Margin"] = pltr_gross_profit / pltr_revenue

if pltr_revenue is not None and pltr_operating_income is not None:
    pltr_margins.loc["Operating Margin"] = pltr_operating_income / pltr_revenue

if pltr_revenue is not None and pltr_net_income is not None:
    pltr_margins.loc["Net Margin"] = pltr_net_income / pltr_revenue

display(pltr_margins)

Empty DataFrame
Columns: []
Index: []

In [40]:
# CELL 30
# Create side-by-side margin comparison table for IBM and PLTR

ibm_margin_latest = margins.iloc[:, -1] if not margins.empty else pd.Series(dtype=float)
pltr_margin_latest = pltr_margins.iloc[:, -1] if not pltr_margins.empty else pd.Series(dtype=float)

comparison_margins = pd.DataFrame({
    "IBM": ibm_margin_latest,
    "PLTR": pltr_margin_latest
})

display(comparison_margins)

Empty DataFrame
Columns: [IBM, PLTR]
Index: []

In [41]:
# CELL 31
# Plot grouped bar chart of latest margins

comparison_margins_reset = comparison_margins.reset_index()
comparison_margins_reset.columns = ["Metric", "IBM", "PLTR"]

comparison_margins_long = comparison_margins_reset.melt(
    id_vars="Metric",
    value_vars=["IBM", "PLTR"],
    var_name="Company",
    value_name="Margin"
)

fig = px.bar(
    comparison_margins_long,
    x="Metric",
    y="Margin",
    color="Company",
    barmode="group",
    title="IBM vs PLTR Margin Comparison"
)

fig.update_layout(template="plotly_white")
fig.show()

In [51]:
import pandas as pd
import plotly.express as px

def get_revenue_series(df_financials, company_name):
    """Extracts historical revenue series from a cleaned financial DataFrame."""
    revenue_data = {}
    if df_financials.empty or 'concept' not in df_financials.columns:
        return pd.Series(revenue_data)

    # Filter for rows where the 'concept' column contains 'revenue'
    # This captures 'us-gaap_Revenues', 'us-gaap_RevenueNet', etc.
    revenue_rows = df_financials[df_financials['concept'].str.contains('revenue', case=False, na=False)]

    if revenue_rows.empty:
        return pd.Series(revenue_data)

    # Iterate through the rows that are identified as revenue
    for _, row in revenue_rows.iterrows():
        # Look for columns that represent fiscal years, typically ending with '(FY)'
        financial_year_cols = [col for col in row.index if 'FY' in col and '-' in col]

        # If a row has multiple financial year columns (like IBM's structure)
        if len(financial_year_cols) > 1:
            for col in financial_year_cols:
                year_label = col.split('-')[0]  # e.g., '2023' from '2023-12-31 (FY)'
                value_str = str(row[col]).replace('$', '').replace(',', '')
                try:
                    value = float(value_str)
                    revenue_data[year_label] = value
                except ValueError:
                    continue
        # If a row has only one financial year column (like PLTR's structure with repeated revenue rows)
        elif len(financial_year_cols) == 1:
            col = financial_year_cols[0]
            year_label = col.split('-')[0]
            value_str = str(row[col]).replace('$', '').replace(',', '')
            try:
                value = float(value_str)
                revenue_data[year_label] = value
            except ValueError:
                continue

    # Sort by year to ensure correct plotting order
    if revenue_data:
        sorted_years = sorted(revenue_data.keys())
        sorted_revenue_data = {year: revenue_data[year] for year in sorted_years}
        return pd.Series(sorted_revenue_data)
    else:
        return pd.Series(revenue_data)

# CELL 32
# Build revenue comparison chart data

# Get IBM historical revenue
ibm_historical_revenue_series = get_revenue_series(income_clean_df, "IBM")

ibm_revenue_df = pd.DataFrame({
    "Period": ibm_historical_revenue_series.index.astype(str),
    "Revenue": ibm_historical_revenue_series.values,
    "Company": "IBM"
})

# Get PLTR historical revenue
pltr_historical_revenue_series = get_revenue_series(pltr_data["income_df"], "PLTR")

pltr_revenue_df = pd.DataFrame({
    "Period": pltr_historical_revenue_series.index.astype(str),
    "Revenue": pltr_historical_revenue_series.values,
    "Company": "PLTR"
})

revenue_comparison_df = pd.concat([ibm_revenue_df, pltr_revenue_df], ignore_index=True)

fig = px.line(
    revenue_comparison_df,
    x="Period",
    y="Revenue",
    color="Company",
    markers=True,
    title="IBM vs PLTR Historical Revenue"
)

fig.update_layout(template="plotly_white")
fig.show()

In [45]:
# CELL 33
# Save comparison outputs

comparison_margins.to_csv(os.path.join(TABLE_DIR, "ibm_pltr_margin_comparison.csv"))
revenue_comparison_df.to_csv(os.path.join(TABLE_DIR, "ibm_pltr_revenue_comparison.csv"), index=False)

print("IBM vs PLTR comparison files saved.")

IBM vs PLTR comparison files saved.

In [46]:
# CELL 34
# Palantir forecast assumptions

pltr_forecast_years = 5

pltr_revenue_growth_rates = [0.24, 0.20, 0.17, 0.14, 0.12]
pltr_operating_margin_assumptions = [0.18, 0.21, 0.24, 0.26, 0.28]
pltr_net_margin_assumptions = [0.16, 0.18, 0.20, 0.22, 0.23]
pltr_fcf_margin_assumptions = [0.22, 0.24, 0.25, 0.26, 0.27]

pltr_wacc = 0.10
pltr_terminal_growth = 0.03

print("Palantir forecast assumptions created.")

Palantir forecast assumptions created.

In [48]:
# CELL 35
# Build Palantir forecast table

# To fix the AttributeError: 'NoneType' object has no attribute 'iloc',
# we need to correctly extract the latest historical revenue for PLTR.
# The `pltr_revenue` variable from CELL 27 is None because `find_row_by_keywords`
# incorrectly searches the index instead of the 'concept' column.
# We will reuse the `get_revenue_series` function defined in CELL 32.

pltr_historical_revenue_series = get_revenue_series(pltr_data["income_df"], "PLTR")

pltr_latest_revenue = 0.0 # Default value
if not pltr_historical_revenue_series.empty:
    pltr_latest_revenue = pltr_historical_revenue_series.iloc[-1]
else:
    print("Warning: Could not extract latest numerical revenue for PLTR. Using 0.0 for forecast.")

pltr_forecast_data = []
pltr_current_revenue = pltr_latest_revenue

for i in range(pltr_forecast_years):
    year_label = f"Year {i+1}"

    growth = pltr_revenue_growth_rates[i]
    op_margin = pltr_operating_margin_assumptions[i]
    net_margin = pltr_net_margin_assumptions[i]
    fcf_margin = pltr_fcf_margin_assumptions[i]

    pltr_current_revenue = pltr_current_revenue * (1 + growth)
    pltr_operating_income_forecast = pltr_current_revenue * op_margin
    pltr_net_income_forecast = pltr_current_revenue * net_margin
    pltr_free_cash_flow_forecast = pltr_current_revenue * fcf_margin

    pltr_forecast_data.append({
        "Year": year_label,
        "Revenue": pltr_current_revenue,
        "Revenue Growth": growth,
        "Operating Margin": op_margin,
        "Operating Income": pltr_operating_income_forecast,
        "Net Margin": net_margin,
        "Net Income": pltr_net_income_forecast,
        "FCF Margin": fcf_margin,
        "Free Cash Flow": pltr_free_cash_flow_forecast
    })

pltr_forecast_df = pd.DataFrame(pltr_forecast_data)
display(pltr_forecast_df)

Warning: Could not extract latest numerical revenue for PLTR. Using 0.0 for forecast.

,Year,Revenue,Revenue Growth,Operating Margin,Operating Income,Net Margin,Net Income,FCF Margin,Free Cash Flow
0,Year 1,0.0,0.24,0.18,0.0,0.16,0.0,0.22,0.0
1,Year 2,0.0,0.20,0.21,0.0,0.18,0.0,0.24,0.0
2,Year 3,0.0,0.17,0.24,0.0,0.20,0.0,0.25,0.0
3,Year 4,0.0,0.14,0.26,0.0,0.22,0.0,0.26,0.0
4,Year 5,0.0,0.12,0.28,0.0,0.23,0.0,0.27,0.0

In [49]:
# CELL 36
# Calculate Palantir DCF

pltr_fcf_values = pltr_forecast_df["Free Cash Flow"].values

pltr_discounted_fcfs = []
for t, fcf in enumerate(pltr_fcf_values, start=1):
    pv = fcf / ((1 + pltr_wacc) ** t)
    pltr_discounted_fcfs.append(pv)

pltr_forecast_df["Discounted FCF"] = pltr_discounted_fcfs

pltr_terminal_fcf = pltr_fcf_values[-1] * (1 + pltr_terminal_growth)
pltr_terminal_value = pltr_terminal_fcf / (pltr_wacc - pltr_terminal_growth)
pltr_discounted_terminal_value = pltr_terminal_value / ((1 + pltr_wacc) ** pltr_forecast_years)

pltr_enterprise_value = pltr_forecast_df["Discounted FCF"].sum() + pltr_discounted_terminal_value

print("Discounted forecast table:")
display(pltr_forecast_df)

print("\nTerminal Value:", pltr_terminal_value)
print("Discounted Terminal Value:", pltr_discounted_terminal_value)
print("Enterprise Value:", pltr_enterprise_value)

Discounted forecast table:

,Year,Revenue,Revenue Growth,Operating Margin,Operating Income,Net Margin,Net Income,FCF Margin,Free Cash Flow,Discounted FCF
0,Year 1,0.0,0.24,0.18,0.0,0.16,0.0,0.22,0.0,0.0
1,Year 2,0.0,0.20,0.21,0.0,0.18,0.0,0.24,0.0,0.0
2,Year 3,0.0,0.17,0.24,0.0,0.20,0.0,0.25,0.0,0.0
3,Year 4,0.0,0.14,0.26,0.0,0.22,0.0,0.26,0.0,0.0
4,Year 5,0.0,0.12,0.28,0.0,0.23,0.0,0.27,0.0,0.0

Terminal Value: 0.0
Discounted Terminal Value: 0.0
Enterprise Value: 0.0

In [52]:
# CELL 37
# Historical vs forecast PLTR revenue chart

# The previous error 'AttributeError: 'NoneType' object has no attribute 'copy'' occurred because
# `pltr_revenue` was None. This was due to the `find_row_by_keywords` function failing to
# correctly extract revenue data from pltr_data["income_df"] as it searched the index,
# not the 'concept' column.

# We will use the already defined `get_revenue_series` function (now improved in CELL 32) to properly extract PLTR's
# historical revenue.

pltr_historical_revenue_series = get_revenue_series(pltr_data["income_df"], "PLTR")

pltr_historical_chart_df = pd.DataFrame()
if not pltr_historical_revenue_series.empty:
    pltr_historical_chart_df = pd.DataFrame({
        "Period": pltr_historical_revenue_series.index.astype(str),
        "Revenue": pltr_historical_revenue_series.values,
        "Type": "Historical"
    })
else:
    print("Warning: No historical revenue data found for PLTR. Historical data will not be plotted.")


pltr_forecast_revenue_chart = pltr_forecast_df[["Year", "Revenue"]].copy()
pltr_forecast_revenue_chart.columns = ["Period", "Revenue"]

pltr_forecast_chart_df = pd.DataFrame({
    "Period": pltr_forecast_revenue_chart["Period"],
    "Revenue": pltr_forecast_revenue_chart["Revenue"],
    "Type": "Forecast"
})

# Combine historical and forecast data. Handle cases where historical_chart_df might be empty.
if not pltr_historical_chart_df.empty:
    pltr_combined_chart_df = pd.concat([pltr_historical_chart_df, pltr_forecast_chart_df], ignore_index=True)
else:
    # If no historical data, just use the forecast data for plotting
    pltr_combined_chart_df = pltr_forecast_chart_df.copy()

if not pltr_combined_chart_df.empty:
    fig = px.line(
        pltr_combined_chart_df,
        x="Period",
        y="Revenue",
        color="Type",
        markers=True,
        title="PLTR Historical and Forecast Revenue"
    )

    fig.update_layout(template="plotly_white")
    fig.show()
else:
    print("No data available to plot PLTR Historical and Forecast Revenue.")

In [53]:
# CELL 38
# Save Palantir forecast outputs

pltr_forecast_df.to_csv(os.path.join(TABLE_DIR, "pltr_forecast.csv"), index=False)

pltr_dcf_summary = pd.DataFrame([{
    "Terminal Value": pltr_terminal_value,
    "Discounted Terminal Value": pltr_discounted_terminal_value,
    "Enterprise Value": pltr_enterprise_value
}])

pltr_dcf_summary.to_csv(os.path.join(TABLE_DIR, "pltr_dcf_summary.csv"), index=False)

print("PLTR forecast and DCF files saved.")

PLTR forecast and DCF files saved.